GroupBelong.delete_all
UserHobby.delete_all
Hobby.delete_all
Group.delete_all
User.delete_all



u1 = User.create(name: 'Asann')
u2 = User.create(name: 'Bsann')
u3 = User.create(name: 'Csann')
u4 = User.create(name: 'Dsann')
u5 = User.create(name: 'Esann')
u6 = User.create(name: 'Fsann')
u7 = User.create(name: 'Gsann')
u8 = User.create(name: 'Hsann')
u9 = User.create(name: 'Isann')
u10 = User.create(name: 'Jsann')
u11 = User.create(name: 'Ksann')
u12 = User.create(name: 'Lsann')
u13 = User.create(name: 'Msann')
u14 = User.create(name: 'Nsann')
u15 = User.create(name: 'Osann')
u16 = User.create(name: 'Psann')
u17 = User.create(name: 'Qsann')
u18 = User.create(name: 'Rsann')


g1 = Group.create(group_name: 'うめぼし')
g2 = Group.create(group_name: 'しゃけ')
g3 = Group.create(group_name: 'こんぶ')
g4 = Group.create(group_name: 'めんたいこ')
g5 = Group.create(group_name: 'からし')


h1 = Hobby.create(hobby_name: '漫画')
h2 = Hobby.create(hobby_name: 'アニメ')
h3 = Hobby.create(hobby_name: '惰眠')
h4 = Hobby.create(hobby_name: 'ツイ廃')
h5 = Hobby.create(hobby_name: '徘徊')
h6 = Hobby.create(hobby_name: 'パチスロ')
h7 = Hobby.create(hobby_name: '競馬')
h8 = Hobby.create(hobby_name: 'ドラクエ')
h9 = Hobby.create(hobby_name: 'アイドル')
h10 = Hobby.create(hobby_name: 'グラボ')


UserHobby.create(user_id: u1.id, hobby_id: h2.id)
UserHobby.create(user_id: u1.id, hobby_id: h4.id)
UserHobby.create(user_id: u1.id, hobby_id: h7.id)
UserHobby.create(user_id: u2.id, hobby_id: h3.id)
UserHobby.create(user_id: u2.id, hobby_id: h5.id)
UserHobby.create(user_id: u2.id, hobby_id: h7.id)
UserHobby.create(user_id: u3.id, hobby_id: h9.id)
UserHobby.create(user_id: u3.id, hobby_id: h7.id)
UserHobby.create(user_id: u3.id, hobby_id: h4.id)
UserHobby.create(user_id: u4.id, hobby_id: h2.id)
UserHobby.create(user_id: u4.id, hobby_id: h3.id)
UserHobby.create(user_id: u4.id, hobby_id: h7.id)
UserHobby.create(user_id: u5.id, hobby_id: h6.id)
UserHobby.create(user_id: u5.id, hobby_id: h1.id)
UserHobby.create(user_id: u5.id, hobby_id: h2.id)
UserHobby.create(user_id: u6.id, hobby_id: h2.id)
UserHobby.create(user_id: u6.id, hobby_id: h1.id)
UserHobby.create(user_id: u6.id, hobby_id: h6.id)
UserHobby.create(user_id: u7.id, hobby_id: h2.id)
UserHobby.create(user_id: u7.id, hobby_id: h6.id)
UserHobby.create(user_id: u7.id, hobby_id: h1.id)


GroupBelong.create(group_id: g4.id, user_id: u1.id)
GroupBelong.create(group_id: g4.id, user_id: u4.id)
GroupBelong.create(group_id: g4.id, user_id: u5.id)
GroupBelong.create(group_id: g4.id, user_id: u2.id)
GroupBelong.create(group_id: g3.id, user_id: u2.id)
GroupBelong.create(group_id: g3.id, user_id: u3.id)
GroupBelong.create(group_id: g3.id, user_id: u4.id)
GroupBelong.create(group_id: g3.id, user_id: u5.id)
GroupBelong.create(group_id: g2.id, user_id: u3.id)
GroupBelong.create(group_id: g2.id, user_id: u6.id)
GroupBelong.create(group_id: g2.id, user_id: u7.id)
GroupBelong.create(group_id: g2.id, user_id: u2.id)
GroupBelong.create(group_id: g1.id, user_id: u2.id)
GroupBelong.create(group_id: g1.id, user_id: u4.id)
GroupBelong.create(group_id: g1.id, user_id: u7.id)
GroupBelong.create(group_id: g1.id, user_id: u5.id)
